name: Lint
on: [push, pull_request] # yamllint disable-line rule:truthy
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: psf/black@stable
      with:
        options: "--check --verbose"
        version: "~= 24.4.0"
    - uses: actions/checkout@v4
    - name: Install yamllint
      run: pip install yamllint==1.33.0
    - name: Lint YAML files
      run: yamllint .
